### ISSUE TITLE
Thảo luận lựa chọn công nghệ, công cụ sử dụng

### ISSUE THREAD

**Issue by BuiHuongGiang0410** [BuiHuongGiang0410/Nhom21-CNPM#1]

**Comment by BuiHuongGiang0410** [comment]
Theo như cuối buổi hôm nay nhóm đã xin ý kiến của thầy và thảo luận thêm, tổng kết được ý kiến như sau:
1. Vì trong team mỗi người có một khả năng khác nhau, thiếu sự đồng nhất về một ngôn ngữ hay một công cụ lập trình cụ thể để có thể làm một web "xịn" theo như yêu cầu của thầy.

2. Dự án cần đề cao : làm việc đúng quy trình, đúng trách nhiệm, ưu tiên sử dụng các công cụ mới, làm sao để tiết kiệm công sức làm việc nhất có thể. Sản phẩm có thể không quá xuất sắc nhưng quan trọng nhất là mọi người được trải nghiệm quá trình phát triển phần mềm càng giống với thực tế càng tốt, có cái nhìn bao quát, làm tốt cả phần việc của mình và để ý cả tới công việc của các bạn trong team, hoàn thiện khả năng làm việc nhóm và thảo luận công việc, nâng cao các kỹ năng cần thiết. 

3. Từ đó rút ra: Ngay lập tức cần tìm một hướng đi mới. Cụ thể về 2 hướng phát triển mới: Lập trình mobile (Crass - Platform) hoặc lập trình web sử dụng Python (Portal) . 

 Trước tiên trong chiều và tối nay, mỗi người sẽ chủ động tìm hiểu về: 
- Crass - Platform (React - Native, Adobe AIR, HAXE)
-  Python (Lập trình mã nguồn mở - Portal)

 Đánh giá mức độ khả thi nếu học một ngôn ngữ, công cụ mới, so sánh với thời gian làm dự án. Sáng ngày mai cùng nhau họp lại  (lịch họp sẽ chốt lại trong tối nay sau khi mọi người cmt ý kiến của mình).

Cảm ơn mọi người ! 
Có tài liệu hay share cả team củng xem nhé !

**Comment by PhanVietHuy** [comment]
ok đã đọc xong, ae có tài liệu k share đi :))

**Comment by Chamiko** [comment]
T vẫn muốn là làm app nên t 1 phiếu vào cái Cross-Platform (React Native) nhé, theo ý kiến t thì t muốn xây dựng 1 app nấu ăn, vì cơ bản t đã có sẵn ý tưởng về giao diện, bố cục, sưu tầm đc các hình ảnh, Cơ mà về mặt chức năng thì t ko có ý tưởng gì hay ho đặc sắc. Nếu m.n cảm thấy là app nấu ăn ok thì phải nghĩ ra thêm cái gì đó để nó ko bị quá đơn giản.

**Comment by PhanVietHuy** [comment]
Cross Platform nhé

**Comment by lindragon1812** [comment]
Làm mobile nhé

**Comment by ndh1812** [comment]
Cross Platform nhưng cần tài liệu để học

**Comment by nguyenbs** [comment]
Cross platform thì theo anh dễ nhất là Adobe AIR, có thể học làm Adobe AIR theo khoác học qua video dạy online của anh:
https://www.youtube.com/watch?v=sTN_4E0r0jc

Các bài tiếp theo của khóa học có thể tìm trong các video của anh Lê Thành post:
https://www.youtube.com/user/ttn1406/videos

Nếu cần thì các anh chị trên ProjectKit có thể hướng dẫn thêm.

Dễ nhì là code ReactNative, nhưng các em phải code JavaScript tốt rồi thì mới làm được.

**Comment by BuiHuongGiang0410** [comment]
Bọn em cảm ơn anh ạ ! Thứ 2 bọn em sẽ họp bàn lại và tiến hành lên kế hoạch viết dần luôn.

**Comment by Chamiko** [comment]
Anh ơi, cho em hỏi là: về cái công nghệ sử dụng ấy ạ, em thấy cộng đồng của Flex nó khá là ít hỗ trợ không nhiều nên khá là khó khăn trong việc debug, còn react thì code ios với android nó là riêng có phải ko ạ? Nó ko build ra đc 2 bản, ko chung code có đúng ko ạ? Nếu dùng Android studio(AS) thì có được không ạ? Vì em thấy AS code bằng Java, mà hầu hết java thì cũng đã quen thuộc với bọn em, cộng đồng hỗ trợ của Java cũng mạnh (như là stackoverflow), với các cái View của nó cũng đã dạng hơn, đẹp hơn, nhiều thư viện hỗ trợ như là trên square.github.io/picasso. Còn về server thì bọn em cũng chưa làm bao giờ, tuy nhiên là hồi hè bọn e có đi thực tập, thấy tại nơi bọn em thực tập, họ làm server bằng PHP, nên em muốn hỏi anh tư vấn một chút về vấn đề này ạ. Em cảm ơn!

**Comment by nguyenbs** [comment]
Nếu chỉ muốn code Java thì không làm cross-platform được đâu, thôi làm 1 hệ điều hành thôi vậy.

Nếu vẫn muốn làm cross platform thì anh có thêm các hướng sau:
- Sử dụng Haxe, ngôn ngữ này cũng dễ code, cộng đồng khá mạnh, code một phát có thể chạy trên cả browser, trên iOS lẫn Android và code bằng IntelliJ
- Sử dụng Xamarin: code bằng C#

Tùy các em nhé.
