### ISSUE TITLE
Chức năng "Bếp Chanel": Xem video dạy nấu ăn

### ISSUE THREAD

**Issue by Chamiko** [BuiHuongGiang0410/Nhom21-CNPM#12]
Chức năng này giống như là 1 kênh tivi, dành cho ai lười đọc :p muốn xem video hoặc trực quan hơn, các video sẽ đươc sưu tầm tư nguồn Youtube nên rất đa dạng.
Chức năng này cần có mạng mới sử dụng được

**Comment by Chamiko** [comment]
Tình hình là đã đổ được cái danh sách video ra, nhưng mà ko chạy được o.O

**Comment by anhbh310** [comment]
Push code lên đây xem

**Comment by Chamiko** [comment]
Đợi Giang push, bh mình push nó cứ hỏi quyền gì ấy, lạ lắm, teamview qua xem hộ cái

**Comment by Chamiko** [comment]
nếu là vấn đề code thì đưa ra gg search trên Stackoverflow là ok

**Comment by ndb1997vn** [comment]
nếu là vấn đề code thì đưa ra gg search trên Stackoverflow là ok mà

**Comment by Chamiko** [comment]
Cơ mà check chiếc các kiểu thấy code chuẩn phết ý chả thấy báo lỗi gì nhưng đến lúc chạy nó lại ghi là "There was problem with the network [400]" trong khi mạng đầy đủ, có google service đủ

**Comment by anhbh310** [comment]
Thế có khi là do gói API rồi, bật những gói API nào

**Comment by Chamiko** [comment]
API data Youtube V3, Google+ API, Contact API

**Comment by Chamiko** [comment]
ơ hay, bảo sao, bật thêm cái Youtube AnalyticsAPI nữa, rồi xin lại key xem

**Comment by anhbh310** [comment]
ơ hay, bảo sao, bật lại Youtube AnalyticsAPI nữa,  r xin lai key xem

**Comment by Chamiko** [comment]
okela để thử
