### ISSUE TITLE
Thảo luận về nội dung đề tài

### ISSUE THREAD

**Issue by BuiHuongGiang0410** [BuiHuongGiang0410/Nhom21-CNPM#2]
Buổi họp sáng ngày mai, chúng ta sẽ thống nhất công nghệ, công cụ sử dụng dựa trên ý kiến và khả năng học mới của mỗi thành viên. Sau đó sẽ thảo luận về nội dung đề tài nên mọi người cố gắng suy nghĩ trước và đưa ra một vài ý tưởng dựa trên những gì đã tìm hiểu nhé !

Thân ái và quyết thắng !!

**Comment by anhbh310** [comment]
Mình nghĩ chúng ta thử làm 1 app điện thoại để đọc truyện online.

**Comment by Chamiko** [comment]
Tui có ý kiến: Làm app dạy nấu ăn :3

**Comment by BuiHuongGiang0410** [comment]
Ý kiến của các bạn đều rất hay, cá nhân mình thấy Handmade mang tính mới mẻ, đối tượng người dùng cụ thể và cũng không quá cầu kỳ và nhiều giao diện như truyện (vì truyện có nhiều thể loại) hơn. Đây cũng là ý kiến của Bảo và Huy. Mặc dù ý kiến của Hiếu và Hoàng Anh về app truyện cũng rất hay nhưng theo ý kiến đa số, chúng ta sẽ là dự án về app dạy làm đồ handmade nhé !
