### ISSUE TITLE
Cập nhật tiến độ (16/11/2017)

### ISSUE THREAD

**Issue by BuiHuongGiang0410** [BuiHuongGiang0410/Nhom21-CNPM#6]

**Comment by Chamiko** [comment]
Đã vẽ xong giao diện màn hình chính, màn hình chứa danh sách các món ăn.
Đã demo thử hiển thị đúng form màn hình chứa thông tin về nguyên liệu, cách làm, sản phẩm của món ăn.
Đang tiến hành ghép code với chức năng danh sách yêu thích.

**Comment by ndb1997vn** [comment]
Đã hoàn thành chức năng danh sách yêu thích, chức năng tìm kiếm món ăn theo từ khóa nhập vào, đang thực hiện ghép code với Bánh

**Comment by Chamiko** [comment]
Cái chức năng "Bếp Chanel" thì vẫn đang làm nhé, với đang chờ thống nhất cùng bên server để kết nối

**Comment by ndb1997vn** [comment]
À với cả, tôi với Bánh ghép code hoàn chỉnh thì cuối cùng là ở trên máy Bánh hết để cho đỡ rối cả thống nhất đc form code, có gì thì Bánh up code hết nhé, còn lại có gì thì vẫn cứ gặp nhau rồi cùng ghép code như cũ.

**Comment by BuiHuongGiang0410** [comment]
Cảm ơn mọi người <3
