### ISSUE TITLE
Chức năng "Bookmark": Danh sách yêu thích

### ISSUE THREAD

**Issue by ndb1997vn** [BuiHuongGiang0410/Nhom21-CNPM#8]
Ở trong nàm hình hiển thị danh sách món ăn theo loại, bên phải mỗi món ăn sẽ có 1 hình trái tim rỗng, tương tự sẽ có trái tim rỗng ở phía trên góc phải trong màn hình hiển thị nội dung món ăn. Khi người dùng cảm thấy yêu thích một món ăn nào đó, sẽ ấn vào hình trái tim rỗng, món ăn được tích trái tim rỗng sẽ được lưu vào danh sách yêu thích, hình trái tim sẽ trở thành đặc (màu đỏ) đồng thời màn hình sẽ hiện ra thông báo "Đã thêm vào danh sách yêu thích", ngược lại khi món ăn đã được yêu thích nhưng người dùng muốn bỏ, ấn vào trái tim đặc, trái tim sẽ trở thành rỗng như ban đầu, đồng thời hiện ra thông báo "Đã xóa khỏi danh sách yêu thích" và món ăn đó được xóa trong danh sách yêu thích.
Để xem danh sách yêu thích, chọn "Bookmark" trong phần menu kéo.

**Comment by BuiHuongGiang0410** [comment]
Chức năng rất hay và thực tế !
