### ISSUE TITLE
Chức năng "Search": tìm kiếm món ăn theo từ khóa nhập vào

### ISSUE THREAD

**Issue by ndb1997vn** [BuiHuongGiang0410/Nhom21-CNPM#9]

**Comment by ndb1997vn** [comment]
Để tìm kiếm một món ăn theo từ khóa nhập vào, chọn trong menu kéo chức năng "search", phía trên màn hình tìm kiếm sẽ có một editText nhập vào từ khóa. sau khi nhập ấn vào icon kính lúp bên cạnh, danh sách món ăn theo từ khóa tìm kiếm sẽ hiển thị. Nếu không có món ăn nào theo từ khóa đã nhập sẽ hiện thông báo "Không có kết quả tìm kiếm cho từ khóa ..."

**Comment by Chamiko** [comment]
EEi, còn nữa, từ khóa nhập vào phải chính xác cả dấu, viết ko dấu nó ko hiện được đúng
